---
title: "Analysis Of Hockey Plus-Minus Using Linear Regression"
author: "Maxwell Brown"
date: "12/4/2017"
output: pdf_document
fontsize: 12pt
geometry: margin =1in

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmutil)
library(tidyverse)
library(stats4)
library(knitr)
library(broom)
library(ggplot2)
library(GGally)
```

```{r echo=FALSE}
data <- read.csv("2007-2017.csv")
data_PP <- read.csv("2007-2017_PP.csv")
#create row names 
rownames(data) <- (data$Player)

```

```{r echo=FALSE}
playerID = match(row.names(data), data_PP$Player)
data$PP_G = data_PP$G[playerID]
data$PP_A = data_PP$A[playerID]
data$PP_G...=data_PP$G...[playerID]
data$PP_GA=data_PP$GA[playerID]
data$PP_GF=data_PP$GF[playerID]
```


```{r echo=FALSE, message=FALSE}
####Adding salary and Position 
#import salary data 
salary <- read_csv("~/Documents/BU/MA 681/Final Project /names.csv", 
    col_names = FALSE)
playerID = match(row.names(data), salary$X1)
data$Salary = salary$X2[playerID]
#make values numbers 
data$Salary = as.numeric(data$Salary)

#seperate Defence from Forwards 
Defence <- read_csv("~/Documents/BU/MA 681/Final Project /NEW/Defence .csv")
##create new column that holds D
Defence$Pos = rep('Defence',length(Defence$Player))
playerID = match(row.names(data), Defence$Player)
data$Pos = Defence$Pos[playerID]
#Identify the forwards 
data$Pos[is.na(data$Pos)] <- 'Forward'
new = subset(data, !is.na(data$Salary))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=3}
#plus-minus box plot by position 
#ggplot(new,aes(x= Pos,y= G...))+
#  geom_boxplot()+
#  ggtitle("Plus-Minus Distribution By Position")+ xlab("Position") + ylab("Plus-Minus")
#summary(new$G...)

ggplot(new,aes(G..., colour = Pos, fill = Pos))+
  geom_density(alpha = 0.1)+
  ggtitle("Plus-Minus Distribution By Position")+ xlab("Plus-Minus") + ylab("Distribution")
```


```{r echo=FALSE}
##linearmodel with Position 
lm_Pos = lm(G...~ Pos + Salary,data=new)
```

```{r echo=FALSE, message = FALSE, warning=FALSE}
library(stringr)
#Plot positions and linear model 

#be able to fit the predicted values 
pred = data.frame(G... = predict(lm_Pos))
playerID = match(row.names(pred), new$Player)
pred$Salary = new$Salary[playerID]
pred$Pos = new$Pos[playerID]
#plot 

caption = "Figure 1: Scatter plot of players accumulated plus-minus form 2008 to 2017 vs accumulated player salary, catagorized by positoin. The linear regression model is overlaid on the data, again catagorized by position"

ggplot(data,aes(x=Salary, y=G..., color = Pos))+
  geom_point()+
  #geom_line(data=B)+
  ggtitle("Career Plus-Minus vs Salary By Position")+ xlab("Salary") + ylab("PM")+
  scale_x_log10()+
  geom_line(data=pred)+
  ggtitle("Accumulated Plus-Minus vs Salary")+ xlab("Player Salary") + ylab("Accumulated Plus-Minus")+
  labs(caption = str_wrap(caption,120))+theme(plot.caption=element_text(size=9, hjust=0, margin=margin(t=15)))
  
```


```{r, echo=FALSE, fig.width=6, fig.height=4}
#summary(lm_Pos)
plot(x=log(new$Salary),y=resid(lm_Pos), main="Residules vs plus-minus",sub="Figure 2: Residules for the linear model against the log scaled salary", xlab = "Salary", ylab = "Residules")
#plot(density(resid(lm_Pos))) # density distribution, clearly more higher negative residules 
#want to look more uniform 
#how to deal wwith skew regression coefi
#AIC(lm_Pos) #AIC decreases 

#overestimating for valuse above 0 +-
```

```{r echo=FALSE, results="asis", message=FALSE, warning=FALSE}
lm_Pos %>% tidy(conf.int = TRUE) %>% knitr::kable(digits = 100, col.names = c("Terms", "Estimates", "Std Error","Wald Statistic","P-Value",".05 Confidence", ".95 Confidence"), caption = "Summary statistics for linear regression to predict accumulated plus-minus")
```

$Average PlusMinus Per Game =\beta_0+\beta_1\times Salary+\beta_2 \times Position + \epsilon$




```{r echo=FALSE, fig.width=4, fig.height=3}
################## +/- per game 
#create +/- per game data
data$G...game = data$G.../data$GP
new = subset(data, !is.na(data$Salary))

#plus-minus box plot by position 
#ggplot(data,aes(x= Pos,y= G...game))+
#  geom_boxplot()

ggplot(new,aes(G...game, colour = Pos, fill = Pos))+
  geom_density(alpha = 0.1)+
  ggtitle("Plus-Minus Distribution By Position")+ xlab("Plus-Minus") + ylab("Distribution")

```

```{r echo=FALSE, fig.width=4, fig.height=3}
#linear model 
lm_Pos_game = lm(G...game~Pos+Salary,data=new)

#Pos<-c(rep('Forward',2),rep('Defence',2))
#C = data.frame(Salary=rep(range(data$Salary,na.rm = TRUE),2),Pos)
#C$G...game <- predict.lm(lm_Pos_game,C)

#summary(lm_Pos_game)
#plot(x=new$G...game,y=resid(lm_Pos_game)) 
#plot(density(resid(lm_Pos_game)))
#AIC(lm_Pos)
#AIC(lm_Pos_game)
```

```{r echo=FALSE, message=FALSE}
#salary vs +/-

playerID = match(row.names(pred), new$Player)
pred$G...game = predict(lm_Pos_game)

caption = "Figure 3: Scatter plot of players average plus-minus form 2008 to 2017 vs accumulated player salary, catagorized by positoin. The linear regression model is overlaid on the data, again catagorized by position"

library(stringr)
ggplot(new, aes(x= Salary, y= G...game, color= Pos))+
  geom_point()+
  #geom_line(data = C)+
  scale_x_log10()+
  geom_line(data=pred)+
  ggtitle("Average Plus-Minus Per Game vs Salary")+ xlab("Player Salary") + ylab("Average Plus-Minus Per Game")+
  labs(caption = str_wrap(caption,120))+theme(plot.caption=element_text(size=9, hjust=0, margin=margin(t=15)))
```

```{r echo=FALSE, fig.width=6, fig.height=4}
plot(x=new$Salary,y=resid(lm_Pos_game),main="Residules vs Plus-Minus Per Game",sub="Figure 4: Residules for the linear model against the average plus-minus per game", xlab = "Average Plus-Minus", ylab = "Residules") 
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
tidy(lm_Pos_game, conf.int = TRUE) %>% knitr::kable(digits = 100, col.names = c("Terms", "Estimates", "Std Error","Wald Statistic","P-Value",".05 Confidence", ".95 Confidence"), caption = "Summary statistics for linear regression to predict average plus-minus per game")
```


$Accumulated PlusMinus =\beta_0+\beta_1\times Zone StartRatio+\beta_2 \times GamesPlayed + \epsilon$



```{r, echo=FALSE, message=FALSE, warning=FALSE}
#### new variables, non scorign related 

pairing = data.frame('Plus_Minus'=new$G...,'Games.Played'=new$GP, 'Penalty.Plus_Minus'= new$iP...,'Time.On.Ice' = new$TOI., 'Zone.Start.Ratio'=new$ZSR, Salary = log10(new$Salary), Pos = new$Pos)
 
           
#testing = data.frame(scale(pairing[1:5]))
#testing = bind_cols(testing, Pos = new$Pos)
#testing = bind_cols(testing, Salary = log10(new$Salary))
caption = "Figure 5: Pairwise plot of accumulated player plus-minus and non scoring statistical measurments including: Games Played, Peantly Plus-Minus, Percentage Time On Ice, Zone Start Ratio, Salary, and Position. The data is catagorized by player position. The diagnal is the density plots, the lower triangular are the scatterplots, the upper trianglular are the correlations and correlations by position."
ggpairs(pairing,aes(colour=Pos))+
  ggtitle("Parwise Plot Of Non Scoring Variables")+
  labs(caption = str_wrap(caption,120))+theme(plot.caption=element_text(size=9, hjust=0, margin=margin(t=15)))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=4}
#install.packages('pander')
library(pander)
oh_boy2 = lm(Plus_Minus ~ Zone.Start.Ratio + Games.Played,pairing)
#summary(oh_boy2)
plot(x=new$G...game,y=resid(oh_boy2), main="Residules vs Plus-Minus Per Game",sub="Figure 4: Residules for the linear model against the accumulated plus-minus per game", xlab = "Accumulated Plus-Minus", ylab = "Residules")

tidy(oh_boy2, conf.int = TRUE) %>% knitr::kable(digits = 100, col.names = c("Terms", "Estimates", "Std Error","Wald Statistic","P-Value",".05 Confidence", ".95 Confidence"), caption = "Summary statistics for linear regression to predict accumulated plus-minus using non scoring stats")
#oh_boy2

```
